# Generated by Django 5.1.4 on 2026-04-29 12:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreport',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='dailyreport',
            index=models.Index(fields=['date', 'user'], name='reports_dai_date_a80b58_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dailyreport',
            unique_together={('user', 'date')},
        ),
    ]
